# Generated by Django 3.2.7 on 2021-09-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('group', models.CharField(max_length=20)),
                ('studentnum', models.CharField(max_length=9)),
                ('modify_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
